### PR TITLE
feat: extended guideline search result type

### PR DESCRIPTION
**Pull request by bojangles-m**

### CODE REVIEW

**Review by SamuelAlev — APPROVED** [review]

**Comment by bojangles-m** [comment]
@Frontify/ecosystem hi, could please one review this PR?

**Review by henser — COMMENTED** [review]
I'm too foreign to this at the moment but I have some questions about the typing here ... and maybe on the existing/previous implementation already.
It seems to me this `GuidelineSearchResultApi` type should provide some sort of abstraction/interface where only the relevant properties for each of it's implementations are applied 🤔  Is it the case that these new `section_*` properties are only relevant for `type` `SECTION` results?

**Comment by SamuelAlev** [comment]
@henser I will merge the PR like it is if you are fine, we anyway need to migrate the method from `appBridge.searchInGuideline` to something along `appBridge.api({ name: "search", payload: [...] })`

**Review by henser — APPROVED** [review]
Sure @SamuelAlev👌 As I said I'm too foreign to this change to be blocking development here 👍 Approved ✅

**Pull request merged**
